/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/NetBeansModuleDevelopment-files/templateTopComponent637.java to edit this template
 */
package com.common;

import java.awt.Color;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import javax.swing.BorderFactory;
import javax.swing.JCheckBox;
import javax.swing.SwingUtilities;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import org.apache.commons.lang3.StringUtils;
import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.filesystems.FileChooserBuilder;
import org.openide.filesystems.FileObject;
import org.openide.loaders.DataObject;
import org.openide.nodes.Node;
import org.openide.windows.TopComponent;
import org.openide.util.NbBundle.Messages;
import org.netbeans.api.project.Project;
import org.netbeans.api.project.SourceGroup;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(
        dtd = "-//com.common//DatLTPluginControlBoard//EN",
        autostore = false
)
@TopComponent.Description(
        preferredID = "DatLTPluginControlBoardTopComponent",
        //iconBase="SET/PATH/TO/ICON/HERE",
        persistenceType = TopComponent.PERSISTENCE_ALWAYS
)
@TopComponent.Registration(mode = "navigator", openAtStartup = false)
@ActionID(category = "Window", id = "com.common.DatLTPluginControlBoardTopComponent")
//@ActionReference(path = "Menu/Window" /*, position = 333 */)
@TopComponent.OpenActionRegistration(
        displayName = "#CTL_DatLTPluginControlBoardAction",
        preferredID = "DatLTPluginControlBoardTopComponent"
)
@Messages({
    "CTL_DatLTPluginControlBoardAction=DatLTPluginControlBoard",
    "CTL_DatLTPluginControlBoardTopComponent=Control Board Window",
    "HINT_DatLTPluginControlBoardTopComponent=This is a DatLT's Plugin Control Board window"
})
public final class DatLTPluginControlBoardTopComponent extends TopComponent {

    private Map<String, String> wMapCHB = new HashMap<>();

    public DatLTPluginControlBoardTopComponent() {
        initComponents();
        setName(Bundle.CTL_DatLTPluginControlBoardTopComponent());
        setToolTipText(Bundle.HINT_DatLTPluginControlBoardTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtFilePath = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        btnSync = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextPane();
        chbMoelaCmn = new javax.swing.JCheckBox();
        chbMoelaSQL = new javax.swing.JCheckBox();
        chbMoelaGym = new javax.swing.JCheckBox();
        chbMoelaCheck = new javax.swing.JCheckBox();
        chbAll = new javax.swing.JCheckBox();
        btnQuickPath = new javax.swing.JButton();
        chbBatBase = new javax.swing.JCheckBox();
        chbJmSysBase = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        chbAutoAlign = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        txtTabQuantity = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSQL = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtCode = new javax.swing.JTextArea();
        btnSQLToCode = new javax.swing.JButton();
        btnCodeToSQL = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(300, 350));

        jLabel1.setBackground(new java.awt.Color(153, 204, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setLabelFor(this);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.jLabel1.text")); // NOI18N
        jLabel1.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.jLabel1.toolTipText")); // NOI18N
        jLabel1.setMaximumSize(new java.awt.Dimension(600, 20));

        jPanel1.setRequestFocusEnabled(false);
        jPanel1.setLayout(new java.awt.GridBagLayout());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel4, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.jLabel4.text")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 0);
        jPanel1.add(jLabel4, gridBagConstraints);

        txtFilePath.setText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.txtFilePath.text")); // NOI18N
        txtFilePath.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.txtFilePath.toolTipText")); // NOI18N
        txtFilePath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFilePathActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(txtFilePath, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(btnBrowse, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.btnBrowse.text")); // NOI18N
        btnBrowse.setAlignmentY(0.0F);
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel1.add(btnBrowse, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(btnSync, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.btnSync.text")); // NOI18N
        btnSync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSyncActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHEAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 5);
        jPanel1.add(btnSync, gridBagConstraints);

        txtLog.setEditable(false);
        txtLog.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.txtLog.toolTipText")); // NOI18N
        jScrollPane1.setViewportView(txtLog);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(jScrollPane1, gridBagConstraints);

        chbMoelaCmn.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(chbMoelaCmn, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbMoelaCmn.text")); // NOI18N
        chbMoelaCmn.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbMoelaCmn.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 0, 10);
        jPanel1.add(chbMoelaCmn, gridBagConstraints);

        chbMoelaSQL.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(chbMoelaSQL, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbMoelaSQL.text")); // NOI18N
        chbMoelaSQL.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbMoelaSQL.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 10);
        jPanel1.add(chbMoelaSQL, gridBagConstraints);

        chbMoelaGym.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(chbMoelaGym, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbMoelaGym.text")); // NOI18N
        chbMoelaGym.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbMoelaGym.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 10);
        jPanel1.add(chbMoelaGym, gridBagConstraints);

        chbMoelaCheck.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(chbMoelaCheck, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbMoelaCheck.text")); // NOI18N
        chbMoelaCheck.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbMoelaCheck.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 10);
        jPanel1.add(chbMoelaCheck, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(chbAll, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbAll.text")); // NOI18N
        chbAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chbAllActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 0, 5);
        jPanel1.add(chbAll, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(btnQuickPath, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.btnQuickPath.text")); // NOI18N
        btnQuickPath.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.btnQuickPath.toolTipText")); // NOI18N
        btnQuickPath.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuickPathActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 19, 0, 0);
        jPanel1.add(btnQuickPath, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(chbBatBase, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbBatBase.text")); // NOI18N
        chbBatBase.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbBatBase.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 3, 0, 10);
        jPanel1.add(chbBatBase, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(chbJmSysBase, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbJmSysBase.text")); // NOI18N
        chbJmSysBase.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbJmSysBase.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 11, 0, 10);
        jPanel1.add(chbJmSysBase, gridBagConstraints);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.jPanel1.TabConstraints.tabTitle"), jPanel1); // NOI18N

        jLabel2.setLabelFor(chbAutoAlign);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.jLabel2.text")); // NOI18N
        jLabel2.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.jLabel2.toolTipText")); // NOI18N

        chbAutoAlign.setSelected(true);
        org.openide.awt.Mnemonics.setLocalizedText(chbAutoAlign, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbAutoAlign.text")); // NOI18N
        chbAutoAlign.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbAutoAlign.toolTipText")); // NOI18N
        chbAutoAlign.setRolloverEnabled(false);

        jLabel3.setLabelFor(txtTabQuantity);
        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.jLabel3.text")); // NOI18N
        jLabel3.setAutoscrolls(true);

        txtTabQuantity.setText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.txtTabQuantity.text")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chbAutoAlign))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTabQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 113, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(chbAutoAlign))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtTabQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(213, Short.MAX_VALUE))
        );

        chbAutoAlign.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.chbAutoAlign.AccessibleContext.accessibleName")); // NOI18N

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.jPanel3.TabConstraints.tabTitle"), jPanel3); // NOI18N

        jPanel2.setLayout(new java.awt.GridBagLayout());

        txtSQL.setColumns(20);
        txtSQL.setLineWrap(true);
        txtSQL.setRows(5);
        txtSQL.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.txtSQL.toolTipText")); // NOI18N
        jScrollPane2.setViewportView(txtSQL);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        jPanel2.add(jScrollPane2, gridBagConstraints);

        txtCode.setColumns(20);
        txtCode.setLineWrap(true);
        txtCode.setRows(5);
        txtCode.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.txtCode.toolTipText")); // NOI18N
        jScrollPane3.setViewportView(txtCode);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 6, 0);
        jPanel2.add(jScrollPane3, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(btnSQLToCode, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.btnSQLToCode.text")); // NOI18N
        btnSQLToCode.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.btnSQLToCode.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 35, 9, 35);
        jPanel2.add(btnSQLToCode, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(btnCodeToSQL, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.btnCodeToSQL.text")); // NOI18N
        btnCodeToSQL.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.btnCodeToSQL.toolTipText")); // NOI18N
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 35, 9, 35);
        jPanel2.add(btnCodeToSQL, gridBagConstraints);

        org.openide.awt.Mnemonics.setLocalizedText(btnReset, org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.btnReset.text")); // NOI18N
        btnReset.setToolTipText(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.btnReset.toolTipText")); // NOI18N
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(9, 35, 9, 35);
        jPanel2.add(btnReset, gridBagConstraints);

        jTabbedPane1.addTab(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.jPanel2.TabConstraints.tabTitle"), jPanel2); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        jTabbedPane1.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.jTabbedPane1.AccessibleContext.accessibleName")); // NOI18N
        jTabbedPane1.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(DatLTPluginControlBoardTopComponent.class, "DatLTPluginControlBoardTopComponent.jTabbedPane1.AccessibleContext.accessibleDescription")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    private void btnSyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyncActionPerformed
        // 0.Var
        String wPath = StringUtils.trimToEmpty(txtFilePath.getText());
        Color wGreenColor =  new Color(0, 150, 0);
        Color wMediumBlue = new Color(0, 0, 205);
        // 1. Xóa log cũ
        txtLog.setText("");

        if (StringUtils.isNotBlank(wPath)) {
            appendLog("********** START SYNCING JAR FILES **********", wGreenColor, false);

            if (!(chbMoelaCmn.isSelected() || chbMoelaSQL.isSelected() || chbMoelaGym.isSelected() || chbMoelaCheck.isSelected())) {
                appendLog("You haven't selected any files to sync!", new Color(204, 153, 0), false);
                setCheckBoxStatus(chbMoelaCmn, false, true);
                setCheckBoxStatus(chbMoelaSQL, false, true);
                setCheckBoxStatus(chbMoelaGym, false, true);
                setCheckBoxStatus(chbMoelaCheck, false, true);
                return;
            } else {
                setCheckBoxStatus(chbMoelaCmn, false, false);
                setCheckBoxStatus(chbMoelaSQL, false, false);
                setCheckBoxStatus(chbMoelaGym, false, false);
                setCheckBoxStatus(chbMoelaCheck, false, false);
            }

            // 2. Chạy logic nặng trong một luồng riêng để không làm đơ UI
            new Thread(new Runnable() {
                @Override
                public void run() {
                    try {
                        List<String> wFileNameCopySuccess = new ArrayList<>();
                        List<String> wFileNameCopyFail = new ArrayList<>();
                        Path wPathOri = Paths.get(wPath);
                        Path wPathTar = Paths.get(wPath, "JarRelease");

                        // Kiểm tra folder gốc
                        appendLog("Checking target path...", null, true);
                        if (wPathOri.isAbsolute() && Files.isDirectory(wPathOri) && Files.exists(wPathOri)) {
                            appendLog("Source path is valid!", wMediumBlue, true);
                        } else {
                            appendLog("Invalid source path! Please select the correct execution folder...", Color.RED, true);
                            return;
                        }

                        if (wPathTar.isAbsolute() && Files.isDirectory(wPathTar) && Files.exists(wPathTar)) {
                            appendLog("Target path is valid!", wMediumBlue, true);
                        } else {
                            appendLog("Invalid target path! Please select the correct execution folder...", Color.RED, true);
                            return;
                        }

                        
                        // Kiểm tra và di chuyển file
                        if (chbMoelaCmn.isSelected()) {
                            if (copyFileCustom(wPathOri, wPathTar, Const.MoveFileName.MOELACMN)) {
                                wFileNameCopySuccess.add(Const.MoveFileName.MOELACMN);
                            } else {
                                wFileNameCopyFail.add(Const.MoveFileName.MOELACMN);
                            }
                        }

                        if (chbMoelaSQL.isSelected()) {
                            if (copyFileCustom(wPathOri, wPathTar, Const.MoveFileName.MOELASQL)) {
                                wFileNameCopySuccess.add(Const.MoveFileName.MOELASQL);
                            } else {
                                wFileNameCopyFail.add(Const.MoveFileName.MOELASQL);
                            }
                        }

                        if (chbMoelaGym.isSelected()) {
                            if (copyFileCustom(wPathOri, wPathTar, Const.MoveFileName.MOELAGYM)) {
                                wFileNameCopySuccess.add(Const.MoveFileName.MOELAGYM);
                            } else {
                                wFileNameCopyFail.add(Const.MoveFileName.MOELAGYM);
                            }
                        }

                        if (chbMoelaCheck.isSelected()) {
                            if (copyFileCustom(wPathOri, wPathTar, Const.MoveFileName.MOELACHECK)) {
                                wFileNameCopySuccess.add(Const.MoveFileName.MOELACHECK);
                            } else {
                                wFileNameCopyFail.add(Const.MoveFileName.MOELACHECK);
                            }
                        }

                        if (chbBatBase.isSelected()) {
                            if (copyFileCustom(wPathOri, wPathTar, Const.MoveFileName.BATBASE)) {
                                wFileNameCopySuccess.add(Const.MoveFileName.BATBASE);
                            } else {
                                wFileNameCopyFail.add(Const.MoveFileName.BATBASE);
                            }
                        }

                        if (chbJmSysBase.isSelected()) {
                            if (copyFileCustom(wPathOri, wPathTar, Const.MoveFileName.JMSYSBASE)) {
                                wFileNameCopySuccess.add(Const.MoveFileName.JMSYSBASE);
                            } else {
                                wFileNameCopyFail.add(Const.MoveFileName.JMSYSBASE);
                            }
                        }

                        appendLog("********** SYNC COMPLETED **********", wGreenColor, false);
                        wFileNameCopySuccess.forEach(wMess -> appendLog("✔ " + wMess + Const.Extension.JAR, wGreenColor, false));
                        wFileNameCopyFail.forEach(wMess -> appendLog("✘ " + wMess + Const.Extension.JAR, Color.RED, false));
                    } catch (Exception e) {
                        appendLog("EXECUTION ERROR: " + e.getMessage(), Color.RED, true);
                        appendLog("Please contact the developer for support!", Color.BLUE, true);
                    }
                }
            }).start();
        } else {
            appendLog("PLEASE SELECT AN EXECUTION FOLDER...", Color.RED, false);
        }
    }//GEN-LAST:event_btnSyncActionPerformed

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // Tạo bộ dựng hộp thoại chọn file
        File file = new FileChooserBuilder("DatLT-MoveFile-Picker")
        .setTitle("Select Target Directory")
        .setDirectoriesOnly(true) // Chỉ cho chọn Folder, đổi thành false nếu muốn chọn File
        .showOpenDialog();

        if (file != null) {
            // Đưa đường dẫn đã chọn vào TextField
            txtFilePath.setText(file.getAbsolutePath());
        }
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void txtFilePathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFilePathActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFilePathActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnQuickPathActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuickPathActionPerformed
        resetLog();
        String wKey = "DEV_SHARE";
        String wCurrentFilePath = getCurrentFilePath();
        Color wOchreC = new Color(204, 153, 51);

        if (wCurrentFilePath.contains(wKey)) {
            String wResult = wCurrentFilePath.substring(0, wCurrentFilePath.indexOf(wKey) + wKey.length());

            txtFilePath.setText(StringUtils.EMPTY);
            txtFilePath.setText(wResult);
            appendLog("From: " + wCurrentFilePath, wOchreC, false);
        } else {
            appendLog("Unknown error: " + wCurrentFilePath, Color.RED, false);
        }
    }//GEN-LAST:event_btnQuickPathActionPerformed

    private void chbAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chbAllActionPerformed
        if (chbAll.isSelected()) {
            chbMoelaCmn.setSelected(true);
            chbMoelaSQL.setSelected(true);
            chbMoelaGym.setSelected(true);
            chbMoelaCheck.setSelected(true);
            chbBatBase.setSelected(true);
            chbJmSysBase.setSelected(true);
        } else {
            chbMoelaCmn.setSelected(false);
            chbMoelaSQL.setSelected(false);
            chbMoelaGym.setSelected(false);
            chbMoelaCheck.setSelected(false);
            chbBatBase.setSelected(false);
            chbJmSysBase.setSelected(false);
        }
    }//GEN-LAST:event_chbAllActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnCodeToSQL;
    private javax.swing.JButton btnQuickPath;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSQLToCode;
    private javax.swing.JButton btnSync;
    private javax.swing.JCheckBox chbAll;
    private javax.swing.JCheckBox chbAutoAlign;
    private javax.swing.JCheckBox chbBatBase;
    private javax.swing.JCheckBox chbJmSysBase;
    private javax.swing.JCheckBox chbMoelaCheck;
    private javax.swing.JCheckBox chbMoelaCmn;
    private javax.swing.JCheckBox chbMoelaGym;
    private javax.swing.JCheckBox chbMoelaSQL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea txtCode;
    private javax.swing.JTextField txtFilePath;
    private javax.swing.JTextPane txtLog;
    private javax.swing.JTextArea txtSQL;
    private javax.swing.JTextField txtTabQuantity;
    // End of variables declaration//GEN-END:variables
    @Override
    public void componentOpened() {
        // TODO add custom code on component opening
    }

    @Override
    public void componentClosed() {
        // TODO add custom code on component closing
    }

    void writeProperties(java.util.Properties p) {
        // better to version settings since initial version as advocated at
        // http://wiki.apidesign.org/wiki/PropertyFiles
        p.setProperty("version", "1.0");
        // TODO store your settings
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
        // TODO read your settings according to their version
    }

    /**
     * Lấy index tab
     *
     */
    public int getSelectedIndex(int pTabIdx) {
        return jTabbedPane1.getSelectedIndex();
    }

    /**
     * Thiết lập tab index
     * 
     */
    public void setSelectedIndex(int pTabIdx) {
        jTabbedPane1.setSelectedIndex(pTabIdx);
    }

    /**
     * Lấy tất cả biến số của tab Align Comments
     * 
     * @return 
     */
    public Map<String, Object> getVar(int pTabIdx) {
        Map<String, Object> wMapR = new HashMap<>();

        switch (pTabIdx) {
            case 0:
                break;
            case 1:
                wMapR.put("chbAutoAlign", chbAutoAlign.isSelected());             // Auto align format
                wMapR.put("txtTabQuantity", txtTabQuantity.getText());            // Số Tab muốn giữa code và comment

                break;
            default:
                throw new AssertionError();
        }

        return wMapR;
    }

    /**
     * Xuất log (dùng đa luồng)
     * 
     * @param msg nội dung log
     * @param c màu chữ (null = Color.BLACK)
     */
    public void appendLog(String msg, Color c, boolean includeTimestamp) {
        // Kiểm tra xem có đang ở EDT không, nếu có thì chạy luôn, nếu không thì dùng invokeLater
        if (SwingUtilities.isEventDispatchThread()) {
            updateLogInternal(msg, c, includeTimestamp);
        } else {
            SwingUtilities.invokeLater(() -> updateLogInternal(msg, c, includeTimestamp));
        }
    }

    /**
     * Thiết lập nội dung log
     *
     * @param msg nội dung log
     * @param c màu chữ (null = Color.BLACK)
     * @param includeTimestamp Xuất log kèm ngày giờ (true: có, false: không)
     */
    private void updateLogInternal(String msg, Color c, boolean includeTimestamp) {
        if (txtLog != null && txtLog.isDisplayable()) {
            try {
                String wMsg;

                if (includeTimestamp) {
                    final DateTimeFormatter LOG_FORMATTER = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm:ss.SSS");
                    String timestamp = LocalDateTime.now().format(LOG_FORMATTER);
                    wMsg = String.format("%s | %s", timestamp, msg);
                } else {
                    wMsg = msg;
                }

                StyledDocument doc = txtLog.getStyledDocument();
                SimpleAttributeSet sas = new SimpleAttributeSet();

                // Dùng Color.BLACK mặc định nếu c truyền vào là null
                Color wColor = (c == null) ? Color.BLACK : c;
                StyleConstants.setForeground(sas, wColor);

                doc.insertString(doc.getLength(), wMsg + "\n", sas);

                // Đảm bảo cuộn xuống cuối cùng
                txtLog.setCaretPosition(doc.getLength());
            } catch (BadLocationException e) {
                System.err.println("Lỗi UI Log: " + msg);
            }
        }
    }

    public boolean copyFileCustom(Path sourcePath, Path targetFolderPath, String pFileName) {
        final Color wGreenColor = new Color(0, 150, 0);
        final String wMessFileIsExists = "File is valid.";
        final String wMessFileIsNotExists = "File does not exist. Make sure the project has been built.";

        // Kiểm tra và di chuyển file
        appendLog("Checking file: dist/" + pFileName + Const.Extension.JAR, null, true);
        Path wMoelaCmnPath = Paths.get(sourcePath.toString(), "Checkin", pFileName, "dist", pFileName + Const.Extension.JAR);
        if (Files.exists(wMoelaCmnPath)) {
            appendLog(wMessFileIsExists, wGreenColor, true);

            // Di chuyển file
            copyFile(wMoelaCmnPath, targetFolderPath);
            return true;
        } else {
            appendLog(wMessFileIsNotExists, Color.RED, true);
            return false;
        }
    }

    /**
     * Sao chép file
     * 
     * @param sourcePath Path file copy
     * @param targetFolderPath Đích path folder copy
     */
    public void copyFile(Path sourcePath, Path targetFolderPath) {
        try {
            // Tạo đường dẫn đầy đủ của file trong thư mục đích
            Path targetFile = targetFolderPath.resolve(sourcePath.getFileName());

            appendLog("Copying file: " + sourcePath.getFileName(), Color.BLACK, true);

            // 1. Kiểm tra file nguồn
            if (!Files.exists(sourcePath)) {
                appendLog("ERROR: Source file not found!", Color.RED, true);
                return;
            }

            // 2. Kiểm tra thư mục đích có tồn tại và đúng là thư mục không
            if (!Files.exists(targetFolderPath) || !Files.isDirectory(targetFolderPath)) {
                appendLog("ERROR: Target directory does not exist or is invalid!", Color.RED, true);
                return;
            }

            // 3. Thực hiện sao chép
            // Tùy chọn REPLACE_EXISTING để ghi đè nếu file cùng tên đã có ở đó
            Files.copy(sourcePath, targetFile, StandardCopyOption.REPLACE_EXISTING);

            appendLog("Success: Copied " + sourcePath.getFileName() + " to " + targetFolderPath, new Color(0, 128, 0), true);

        } catch (Exception e) {
            appendLog("ERROR: " + e.getMessage(), Color.RED, true);
        }
    }

    private void setCheckBoxStatus(JCheckBox cb, boolean isError, boolean isWarning) {
        if (isError) {
            // Tạo một viền màu đỏ bao quanh CheckBox
            cb.setBorderPainted(true); // Quan trọng: Phải cho phép vẽ border
            cb.setBorder(BorderFactory.createLineBorder(Color.RED, 1));
        } else if (isWarning) {
            // Tạo một viền màu đỏ bao quanh CheckBox
            cb.setBorderPainted(true); // Quan trọng: Phải cho phép vẽ border
            cb.setBorder(BorderFactory.createLineBorder(new Color(204, 153, 0), 1));
        } else {
            // Trả về mặc định (thường là không có viền bao quanh)
            cb.setBorder(null);
            cb.setBorderPainted(false);
        }
        cb.repaint();
    }

    /**
     * Lấy path chỗ đang focus
     * 
     * @return 
     */
    private String getCurrentFilePath() {
        try {
            Node[] wNode = TopComponent.getRegistry().getActivatedNodes();

            FileObject wFO = wNode[0].getLookup().lookup(FileObject.class);
            if (wFO != null) {
                return wFO.getPath();
            }

            DataObject wDdo = wNode[0].getLookup().lookup(DataObject.class);
            if (wDdo != null) {
                return wDdo.getPrimaryFile().getPath();
            }

            Project project = wNode[0].getLookup().lookup(Project.class);
            if (project != null) {
                return project.getProjectDirectory().getPath();
            }

            SourceGroup wSG = wNode[0].getLookup().lookup(SourceGroup.class);
            if (wSG != null) {
                return wSG.getRootFolder().getPath();
            }
            return StringUtils.EMPTY;
        } catch (Throwable t) {
            return t.toString();
        }
    }

    private void resetLog() {
        txtLog.setText(StringUtils.EMPTY);
    }
}
